repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-annotations-complexity,
            flake8_builtins,
            flake8-eradicate,
            flake8_pep3101,
        ]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.1
    hooks:
    -   id: pydocstyle
