version: "3.7"

services:
  tellerbot:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ${DATABASE_PASSWORD_FILENAME}:${DATABASE_PASSWORD_FILENAME}:ro
      - ${TOKEN_FILENAME}:${TOKEN_FILENAME}:ro
      - ${WIF_FILENAME}:${WIF_FILENAME}:ro
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  database:
    image: mongo:4.2.1
    container_name: ${DATABASE_HOST}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD_FILE=${DATABASE_PASSWORD_FILENAME}
    command: mongod --quiet
    ports:
      - 27017
    volumes:
      - ${DATABASE_PASSWORD_FILENAME}:${DATABASE_PASSWORD_FILENAME}:ro
      - ~/data/db:/data/db
